name: Build Docker Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        cd ubuntu-22.04
        docker build . -t gen740/test-ubuntu-22.04:latest
      env:
        DOCKER_BUILDKIT: 1

    - name: Push to docker hub
      env:
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "${DOCKER_HUB_TOKEN}" | docker login -u gen740 --password-stdin
        docker push gen740/test-ubuntu-22.04:latest
