name: Build Docker Image
on:
  push:
    branches:
      - master
jobs:
  dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        cd arch
        docker build .
      env:
        DOCKER_BUILDKIT: 1
