name: Build Docker Image
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ubuntu-22.04
          tags: gen740/ubuntu-22.04:latest
          platforms: linux/amd64,linux/arm64
          push: true
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Build the Docker image
  #     run: |
  #       cd ubuntu-22.04
  #       docker buildx build --build-arg ARCH=arm64 . -t gen740/ubuntu-22.04:latest
  #     env:
  #       DOCKER_BUILDKIT: 1
  #
  #   - name: Push to docker hub
  #     env:
  #       DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     run: |
  #       echo "${DOCKER_HUB_TOKEN}" | docker login -u gen740 --password-stdin
  #       docker push gen740/ubuntu-22.04:latest
  #
  # build-arm:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Build the Docker image
  #     run: |
  #       cd ubuntu-22.04
  #       docker buildx build --platform linux/arm64 --build-arg ARCH=arm64 . -t gen740/ubuntu-22.04:latest
  #     env:
  #       DOCKER_BUILDKIT: 1
  #
  #   - name: Push to docker hub
  #     env:
  #       DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     run: |
  #       echo "${DOCKER_HUB_TOKEN}" | docker login -u gen740 --password-stdin
  #       docker push gen740/ubuntu-22.04:latest
  #
  # build_linuxbrew:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: Build the Docker image
  #     run: |
  #       cd ubuntu-22.04-linuxbrew
  #       docker build . -t gen740/ubuntu-22.04-linuxbrew:latest
  #     env:
  #       DOCKER_BUILDKIT: 1
  #
  #   - name: Push to docker hub
  #     env:
  #       DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  #     run: |
  #       echo "${DOCKER_HUB_TOKEN}" | docker login -u gen740 --password-stdin
  #       docker push gen740/ubuntu-22.04-linuxbrew:latest
